<a href="https://colab.research.google.com/github/ThousandAI/pycs4001/blob/main/class04/class04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **函式**


In [1]:
def get_sum(course,*args):
    scores = sum(args)
    print(f"{course} 總分為: {scores}")
get_sum("Math",30,20,60,80,100,90,70,98)

Math 總分為: 548


In [2]:
def get_sports(sports, **kwargs):
    print(sports)
    print(kwargs)
    for k,v in kwargs.items():
        print(f"{k}: {v}")
get_sports( "basketball",curry=[15,10,5,10], thompson= [20,10,10,5] )

basketball
{'curry': [15, 10, 5, 10], 'thompson': [20, 10, 10, 5]}
curry: [15, 10, 5, 10]
thompson: [20, 10, 10, 5]


# **字典**

In [3]:
# dictionary
dic = {"sports":["basketball", "football"], "name": ["Allie", "Thousand"]}
print(dic["sports"])
print(dic["sports"][0])
# 新增 key
dic["scores"] = [70, 80, 90, 100] # 跟 list 新增方式不一樣，更為簡單
dic["hobby"] = "Reading" # value 也可以只有一個人
print(dic)

['basketball', 'football']
basketball
{'sports': ['basketball', 'football'], 'name': ['Allie', 'Thousand'], 'scores': [70, 80, 90, 100], 'hobby': 'Reading'}


In [4]:
# 迴圈 + 字典
for key in dic.keys():
    print(f"key is: {key}")

key is: sports
key is: name
key is: scores
key is: hobby


In [5]:
for value in dic.values():
    print(f"value is: {value}")

value is: ['basketball', 'football']
value is: ['Allie', 'Thousand']
value is: [70, 80, 90, 100]
value is: Reading


In [6]:
for key, value in dic.items():
    print(f"key is: {key}, and value is: {value}")

key is: sports, and value is: ['basketball', 'football']
key is: name, and value is: ['Allie', 'Thousand']
key is: scores, and value is: [70, 80, 90, 100]
key is: hobby, and value is: Reading


In [7]:
n = int(input())
dic = {}
for i in range(n):
    tem = input().split()
    if tem[0] not in dic:
        dic[tem[0]] = [int(tem[1])]
    else:
        dic[tem[0]] += [int(tem[1])]
print(dic)

7
Harry 37
Json 25
Json 36
Harry 38
Tom 50
Harry 36
Tom 20
{'Harry': [37, 38, 36], 'Json': [25, 36], 'Tom': [50, 20]}


In [8]:
# sorted + 字典 (解答)
dic = {"Harry":32,"Berry":31,"Thousand":21,"Becky":50,"Allie":37}
sorted_tuple = sorted(dic.items(), key=lambda item: item[1])
sorted_dic = {key: value for key, value in sorted_tuple}
print(sorted_dic)

{'Thousand': 21, 'Berry': 31, 'Harry': 32, 'Allie': 37, 'Becky': 50}


# 物件導向 (Object Oriented Programming)

In [ ]:
class Person:
  # 建構子 constructor
  def __init__(self, name, gender):
    self.n = name
    self.g = gender
    print("This is Person Class")
  
  # instance method
  def introduction(self):
    print(f"Hello my name is {self.n}")

In [ ]:
# 物件化 (實體化) instance
p1 = Person(name="Thousand", gender="Male")
p2 = Person(name="Allie", gender="Female")

This is Person Class
This is Person Class


In [ ]:
print(p1.n, p1.g)
print(p2.n, p2.g)

Thousand Male
Allie Female


In [ ]:
p1.introduction()

Hello my name is Thousand


In [ ]:
p2.introduction()

Hello my name is Allie


# **繼承 (Inheritance)**

In [ ]:
class Character:
  def __init__(self, name, gender, weapon="bat"):
    self.lv = 1
    self.exp = 0
    self.n = name
    self.g = gender
    self.w = weapon
    print("This is Character class.")

  def __str__(self):
      return f"Name: {self.n}, Gender: {self.g}, Weapon: {self.w}, Level: {self.lv}, Exp: {self.exp}"

  def attack(self, enemy):
    self.exp += 40
    enemy.hp -= 1
    self.level_up()
    print(f"{self.n} attacked! Level: {self.lv}, Exp: {self.exp}")
  
  def level_up(self):
    if self.exp >= 100:
        self.lv += 1
        self.exp -= 100
        print(f"{self.n} Level up!!!")

In [ ]:
class Enemy:
  def __init__(self):
    self.name = "Monster"
    self.hp = 100

In [ ]:
class Warrior(Character):
  def __init__(self, name, gender, weapon="bat"):
    super().__init__(name, gender, weapon)
    self.sp = 100
    print("This is Warrior Class.")

  def attack(self,enemy):
    super().attack(enemy)
    print("w1")

In [ ]:
class Magician(Character):
  def __init__(self, name, gender, weapon="bat"):
    super().__init__(name, gender, weapon)
    self.mp = 100
    print("This is Magician Class.")

In [ ]:
w1 = Warrior(name="Thousand", gender="Male", weapon="Sword")

This is Character class.
This is Warrior Class.


In [ ]:
print(w1)

Name: Thousand, Gender: Male, Weapon: Sword, Level: 1, Exp: 0


In [ ]:
e = Enemy()

In [ ]:
for i in range(10):
  w1.attack(enemy=e)

Thousand attacked! Level: 1, Exp: 40
w1
Thousand attacked! Level: 1, Exp: 80
w1
Thousand Level up!!!
Thousand attacked! Level: 2, Exp: 20
w1
Thousand attacked! Level: 2, Exp: 60
w1
Thousand Level up!!!
Thousand attacked! Level: 3, Exp: 0
w1
Thousand attacked! Level: 3, Exp: 40
w1
Thousand attacked! Level: 3, Exp: 80
w1
Thousand Level up!!!
Thousand attacked! Level: 4, Exp: 20
w1
Thousand attacked! Level: 4, Exp: 60
w1
Thousand Level up!!!
Thousand attacked! Level: 5, Exp: 0
w1


In [ ]:
# class Warrior(Character):
#     def __init__(self, name, gender, weapon="bat"):
#         self.lv = 1
#         self.exp = 0
#         self.n = name
#         self.g = gender
#         self.w = weapon
#         self.sp = 100
#         print("This is Warrior class.")

#     def __str__(self):
#       return f"Name: {self.n}, Gender: {self.g}, Weapon: {self.w}, Level: {self.lv}, Exp: {self.exp}"

#     def attack(self, enemy):
#       self.exp += 40
#       enemy.hp -= 1
#       self.level_up()
#       print(f"{self.n} attacked! Level: {self.lv}, Exp: {self.exp}")
    
#     def level_up(self):
#       if self.exp >= 100:
#           self.lv += 1
#           self.exp -= 100
#           print(f"{self.n} Level up!!!")

In [ ]:
class Magician:
    def __init__(self, name, gender, weapon="bat"):
        self.lv = 1
        self.exp = 0
        self.n = name
        self.g = gender
        self.w = weapon
        self.mp = 100

    def __str__(self):
      return f"Name: {self.n}, Gender: {self.g}, Weapon: {self.w}, Level: {self.lv}, Exp: {self.exp}"

    def attack(self, enemy):
      self.exp += 40
      enemy.hp -= 1
      self.level_up()
      print(f"{self.n} attacked! Level: {self.lv}, Exp: {self.exp}")
    
    def level_up(self):
      if self.exp >= 100:
          self.lv += 1
          self.exp -= 100
          print(f"{self.n} Level up!!!")

In [ ]:
class Enemy:
  def __init__(self):
    self.name = "Monster"
    self.hp = 100

In [ ]:
warrior1 = Warrior(name = "Thousand", gender = "Male", weapon = "Sword")
warrior2 = Warrior(name = "Allie", gender = "Female", weapon = "Longbow")

This is Warrior class.
This is Warrior class.


In [ ]:
e = Enemy()

In [ ]:
print(f"Warrior: {warrior1}")

Warrior: Name: Thousand, Gender: Male, Weapon: Sword, Level: 1, Exp: 0


In [ ]:
for i in range(5):
  warrior1.attack(enemy = e)

Thousand attacked! Level: 1, Exp: 40
Thousand attacked! Level: 1, Exp: 80
Thousand Level up!!!
Thousand attacked! Level: 2, Exp: 20
Thousand attacked! Level: 2, Exp: 60
Thousand Level up!!!
Thousand attacked! Level: 3, Exp: 0


In [ ]:
e.hp

95

# **Numpy**

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
b = np.array([[1.0,2.0,3.0],[3.2,5.7,8.2]])
print(f"a: {a}")
print(f"a dimension: {a.ndim}")
print(f"a shape: {a.shape}")
print(f"a type: {a.dtype}")
print(f"b: {b}")
print(f"b dimension: {b.ndim}")
print(f"b shape: {b.shape}")
print(f"b type: {b.dtype}")

a: [1 2 3]
a dimension: 1
a shape: (3,)
a type: int64
b: [[1.  2.  3. ]
 [3.2 5.7 8.2]]
b dimension: 2
b shape: (2, 3)
b type: float64


In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
# index/slice/2D
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a[1,2]) # 9
print(a[0,:]) # [1,2,3,4,5,6]
print(a[:,2]) # [3,8]
print(a[0,1:5:2]) # [2,4] (start,stop,step)
a[1,2] = 20
print(a)
a[:,2] = [7,8]
print(a)

9
[1 2 3 4 5 6]
[3 9]
[2 4]
[[ 1  2  3  4  5  6]
 [ 7  8 20 10 11 12]]
[[ 1  2  7  4  5  6]
 [ 7  8  8 10 11 12]]


In [ ]:
# index/slice/3D
a = np.array([[[1,2],[3,5],[7,8]],
              [[1,7],[-3,2],[10,2]],
              [[6,-2],[5,-3],[7,9]],
              [[8,5],[-2,2],[26,-2]],
              [[1,-7],[-3,2],[-5,-2]],])
print(a)
print(a.shape) 
print(a[3,2,0])
print(a[:,1,:])

[[[ 1  2]
  [ 3  5]
  [ 7  8]]

 [[ 1  7]
  [-3  2]
  [10  2]]

 [[ 6 -2]
  [ 5 -3]
  [ 7  9]]

 [[ 8  5]
  [-2  2]
  [26 -2]]

 [[ 1 -7]
  [-3  2]
  [-5 -2]]]
(5, 3, 2)
26
[[ 3  5]
 [-3  2]
 [ 5 -3]
 [-2  2]
 [-3  2]]


In [ ]:
a = np.zeros((3,2), dtype=np.int32)
print(a)

[[0 0]
 [0 0]
 [0 0]]


In [ ]:
x = np.random.rand(3,2)
y = np.random.randint(low=10, high=100, size= (5,2))
print(x)
print(y)

[[0.06131423 0.19529071]
 [0.13354202 0.42739974]
 [0.61545439 0.36585379]]
[[49 83]
 [18 39]
 [54 58]
 [83 21]
 [86 72]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a ** 2)

[[3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[ 1  4  9]
 [16 25 36]]


In [ ]:
a = [1,2,3]
b = [4,5,6]
c = []
for i in range(len(a)):
    c.append(a[i] + b[i])
print(c)
print(a+b)  # 相加是串列相加
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y) # 平行運算

[5, 7, 9]
[1, 2, 3, 4, 5, 6]
[5 7 9]


In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[2,3,1],[5,2,1]])
print(np.matmul(a,b))

[[12  7  3]
 [26 17  7]
 [40 27 11]]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
identity = np.identity(3)
print(np.matmul(a,identity))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
a = np.array([[92,83,56,77,98],[81,53,64,76,60]])
print(np.max(a))

98


In [ ]:
print(np.max(a,axis=0))

[92 83 64 77 98]


In [ ]:
print(np.max(a,axis=1))

[98 81]


In [ ]:
print(np.sum(a, axis=0))

[173 136 120 153 158]


In [ ]:
print(np.sum(a, axis=1))

[406 334]
