<a href="https://colab.research.google.com/github/ThousandAI/pycs4001/blob/main/class07/standardscaler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
x = np.array([1,2,5,1,7,8,10,12,5,6])

In [3]:
scaler = StandardScaler()

In [4]:
scaler.fit_transform(x)

ValueError: ignored

## **Shape**

In [5]:
print(x.shape)

(10,)


In [6]:
x = x.reshape(-1, 1)
print(x)

[[ 1]
 [ 2]
 [ 5]
 [ 1]
 [ 7]
 [ 8]
 [10]
 [12]
 [ 5]
 [ 6]]


## **fit**

In [7]:
scaler.fit(x)

StandardScaler()

In [8]:
sc_x = scaler.transform(x)
print(sc_x)

[[-1.33417245]
 [-1.05030597]
 [-0.19870653]
 [-1.33417245]
 [ 0.36902642]
 [ 0.6528929 ]
 [ 1.22062585]
 [ 1.78835881]
 [-0.19870653]
 [ 0.08515994]]


In [9]:
print(sc_x[:, 0].mean())
print(sc_x[:, 0].std())

-5.967448757360216e-17
1.0


In [10]:
test_x = np.array([1,2,3,5,1,6,8,2])
test_x = test_x.reshape(-1,1)
sc_test_x = scaler.transform(test_x)
print(sc_test_x)

[[-1.33417245]
 [-1.05030597]
 [-0.76643949]
 [-0.19870653]
 [-1.33417245]
 [ 0.08515994]
 [ 0.6528929 ]
 [-1.05030597]]


# **2D Array**

In [11]:
x_2D = np.array([[1,5,2],[7,0,5],[12,3,8], [10,5,3]])
sc_x_2D = scaler.fit_transform(x_2D)
print(sc_x_2D)

[[-1.56501609  0.85518611 -1.09108945]
 [-0.12038585 -1.58820278  0.21821789]
 [ 1.08347268 -0.12216944  1.52752523]
 [ 0.60192927  0.85518611 -0.65465367]]


In [12]:
print(sc_x_2D[:,0].mean())
print(sc_x_2D[:,0].std())

0.0
1.0


In [13]:
print(sc_x_2D[:,1].mean())
print(sc_x_2D[:,1].std())

0.0
0.9999999999999999


In [14]:
print(sc_x_2D[:,2].mean())
print(sc_x_2D[:,2].std())

-2.7755575615628914e-17
1.0
