<a href="https://colab.research.google.com/github/ThousandAI/pycs4001/blob/main/class07/standardscaler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
x = np.array([1,2,5,1,7,8,10,12,5,6])

In [3]:
scaler = StandardScaler()

In [4]:
scaler.fit_transform(x)

ValueError: ignored

## **Shape**

In [4]:
print(x.shape)

(10,)


In [5]:
x = x.reshape(-1, 1)
print(x)

[[ 1]
 [ 2]
 [ 5]
 [ 1]
 [ 7]
 [ 8]
 [10]
 [12]
 [ 5]
 [ 6]]


## **fit**

In [7]:
scaler.fit(x)

StandardScaler()

In [8]:
sc_x = scaler.transform(x)
print(sc_x)

[[-1.33417245]
 [-1.05030597]
 [-0.19870653]
 [-1.33417245]
 [ 0.36902642]
 [ 0.6528929 ]
 [ 1.22062585]
 [ 1.78835881]
 [-0.19870653]
 [ 0.08515994]]


In [9]:
print(sc_x[:, 0].mean())
print(sc_x[:, 0].std())

-5.967448757360216e-17
1.0


In [11]:
test_x = np.array([1,2,3,5,1,6,8,2])
test_x = test_x.reshape(-1,1)
sc_test_x = scaler.transform(test_x)
print(sc_test_x)

[[-1.33417245]
 [-1.05030597]
 [-0.76643949]
 [-0.19870653]
 [-1.33417245]
 [ 0.08515994]
 [ 0.6528929 ]
 [-1.05030597]]
