<a href="https://colab.research.google.com/github/ThousandAI/pycs4001/blob/main/class10/hw4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.zeros((2,3))
B = np.zeros((3,2))

In [4]:
print("A:")
for i in range(2):
  A[i,:] = np.array(list(map(lambda x: int(x), input().split())))
print("B:")
for i in range(3):
  B[i,:] = np.array(list(map(lambda x: int(x), input().split())))

A:
2 3 5
5 7 8
B:
1 2
3 10
2 6


In [5]:
print(A)

[[2. 3. 5.]
 [5. 7. 8.]]


In [6]:
print(B)

[[ 1.  2.]
 [ 3. 10.]
 [ 2.  6.]]


In [7]:
ans = np.matmul(A,B)
print(ans)

[[ 21.  64.]
 [ 42. 128.]]
